[project]
name = "funlbm"
version = "1.2.43"
description = "funlbm"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [ "funtable>=1.0.25", "funtecplot>=1.0.1", "funutil>=1.0.14", "funvtk>=1.0.9", "h5py>=3.13.0", "nicegui>=2.15.0", "pandas>=2.2.3", "scipy>=1.13.1", "torch>=2.2.0", "transforms3d>=0.4.2", "typer>=0.15.2",]
[[project.authors]]
name = "牛哥"
email = "niuliangtao@qq.com"

[[project.authors]]
name = "farfarfun"
email = "farfarfun@qq.com"

[[project.maintainers]]
name = "牛哥"
email = "niuliangtao@qq.com"

[[project.maintainers]]
name = "farfarfun"
email = "farfarfun@qq.com"

[project.scripts]
funlbm = "funlbm.server:funlbm"

[project.urls]
Organization = "https://github.com/farfarfun"
Repository = "https://github.com/farfarfun/funlbm"
Releases = "https://github.com/farfarfun/funlbm/releases"

[tool.setuptools]
license-files = []

[tool.uv]
package = true
[[tool.uv.index]]
name = "packages-pypi"
url = "https://packages.aliyun.com/5fc5eb115dbd287006145e5f/pypi/funpy"

