#https://github.com/marketplace/actions/hub-mirror-action
name: syncToGitee
on:
  push:
    tags:
      - '*'
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master

        with:
          src: github/farfarfun
          dst: gitee/farfarfun
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          account_type: org
          static_list: 'funlbm'
